services:
  clinic-postgres:
    image: postgres:16
    container_name: clinic-postgres
    environment:
      POSTGRES_DB: clinicdb
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinic123
    ports:
      - "5433:5432"
    volumes:
      - clinic_pg_data:/var/lib/postgresql/data

volumes:
  clinic_pg_data: